const CHANGE_PRESENTATION_TITLE = 'CHANGE_PRESENTATION_TITLE'
const IMPORT_PRESENTATION = 'IMPORT_PRESENTATION'
const EXPORT_PRESENTATION = 'EXPORT_PRESENTATION'
const CONVERT_TO_PDF_PRESENTATION = 'CONVERT_TO_PDF_PRESENTATION'

const ADD_SLIDE = 'ADD_SLIDE'
const CREATE_SLIDE = 'CREATE_SLIDE'
const SELECT_SLIDE = 'SELECT_SLIDE'
const SET_BACKGROUND_SLIDE = 'SET_BACKGROUND_SLIDE'
const MOVE_SLIDE = 'MOVE_SLIDE'
const UNSELECT_SLIDE = 'UNSELECT_SLIDE'
const DELETE_SLIDE = 'DELETE_SLIDE'

const SELECT_OBJECT = 'SELECT_OBJECT'
const UNSELECT_OBJECT = 'UNSELECT_OBJECT' 
const DELETE_OBJECT = 'DELETE_OBJECT'
const RESIZE_OBJECT = 'RESIZE_OBJECT'
const MOVE_OBJECT = 'MOVE_OBJECT'

const CREATE_FIGURE = 'CREATE_FIGURE_RECTANGLE'
const SET_COLOR_FIGURE = 'SET_COLOR_FIGURE'
const CHANGE_OPACITY = 'CHANGE_OPACITY'
const SET_STROKECOLOR_FIGURE = 'SET_STROKECOLOR_RECTANGLE'

const CREATE_IMAGE = 'CREATE_IMAGE'
const CHANGE_OPACITY_IMAGE = 'CHANDE_OPACITY_IMAGE'
const SET_IMAGE_BACKGROUND = 'SET_IMAGE_BACKGROUND'

const CREATE_TEXTBOX = 'CREATE_TEXTBOX'
const SET_TEXT = 'SET_TEXT'
const CHANGE_TEXT_COLOR = 'CHANGE_TEXT_COLOR'
const CHANGE_TEXT_BACKGROUND = 'CHANGE_TEXT_BACKGROUND'
const CHANGE_TEXT_SIZE = 'CHANGE_TEXT_SIZE'
const CHANGE_FONT = 'CHANGE_FONT'
const CHANGE_TEXT_STYLE = 'CHANGE_TEXT_STYLE'
const CHANGE_TEXT_ALIGNMENT = 'CHANGE_TEXT_ALIGNMENT'

/* 
    Презентация, Слайды, Объекты, Фигуры(круг/квадрат/треугольник), Картинки, текстбоксы 
*/

export {
    IMPORT_PRESENTATION,
    CHANGE_PRESENTATION_TITLE,
    ADD_SLIDE,
    CREATE_SLIDE,
    SELECT_SLIDE,
    UNSELECT_SLIDE,
    SET_BACKGROUND_SLIDE,
    MOVE_SLIDE,
    DELETE_SLIDE,
    SELECT_OBJECT,
    UNSELECT_OBJECT,
    DELETE_OBJECT,
    RESIZE_OBJECT,
    MOVE_OBJECT,
    CREATE_FIGURE,
    SET_COLOR_FIGURE,
    CHANGE_OPACITY,
    SET_STROKECOLOR_FIGURE,
    CREATE_IMAGE,
    CHANGE_OPACITY_IMAGE,
    SET_IMAGE_BACKGROUND,
    CREATE_TEXTBOX,
    SET_TEXT,
    CHANGE_TEXT_COLOR,
    CHANGE_TEXT_BACKGROUND,
    CHANGE_TEXT_SIZE,
    CHANGE_FONT,
    CHANGE_TEXT_STYLE,
    CHANGE_TEXT_ALIGNMENT,
}