const CHANGE_PRESENTATION_TITLE = 'CHANGE_PRESENTATION_TITLE'
const IMPORT_PRESNTATION = 'IMPORT_PRESNTATION'
const EXPORT_PRESENTATION = 'EXPORT_PRESENTATION'
const CONVERT_TO_PDF_PRESENTATION = 'CONVERT_TO_PDF_PRESENTATION'

const CREATE_SLIDE = 'CREATE_SLIDE'
const SELECT_SLIDE = 'SELECT_SLIDE'
const SET_BACKGROUND_COLOR_SLIDE = 'SET_BACKGROUND_COLOR_SLIDE'
const SET_BACKGROUND_IMAGE_SLIDE = 'SET_BACKGROUND_IMAGE_SLIDE'
const MOVE_SLIDE = 'MOVE_SLIDE'
const UNSELECT_SLIDE = 'UNSELECT_SLIDE'
const DELETE_SLIDE = 'DELETE_SLIDE'

const CREATE_OBJECT = 'CREATE_OBJECT'
const SELECT_OBJECT = 'SELECT_OBJECT'
const UNSELECT_OBJECT = 'UNSELECT_OBJECT' 
const DELETE_OBJECT = 'DELETE_OBJECT'
const RESIZE_OBJECT = 'RESIZE_OBJECT'
const MOVE_OBJECT = 'MOVE_OBJECT'

const CREATE_FIGURE_RECTANGLE = 'CREATE_FIGURE_RECTANGLE'
const SET_COLOR_FIGURE = 'SET_COLOR_FIGURE'
const CHANGE_OPACITY = 'CHANGE_OPACITY'
const SET_STROKECOLOR_FIGURE = 'SET_STROKECOLOR_RECTANGLE'
const CREATE_FIGURE_TRIANGLE = 'CREATE_FIGURE_TRIANGLE'
const CREATE_FIGURE_CIRCLE = 'CREATE_FIGURE_CIRCLE'

/* 
    Презентация, Слайды, Объекты, Фигуры(круг/квадрат/треугольник), Картинки, текстбоксы 
*/

export {
    CHANGE_PRESENTATION_TITLE,
    CREATE_SLIDE,
    SELECT_SLIDE,
    UNSELECT_SLIDE,
    SET_BACKGROUND_COLOR_SLIDE,
    SET_BACKGROUND_IMAGE_SLIDE,
    MOVE_SLIDE,
    DELETE_SLIDE,
    CREATE_OBJECT,
    SELECT_OBJECT,
    UNSELECT_OBJECT,
    DELETE_OBJECT,
    RESIZE_OBJECT,
    MOVE_OBJECT,
    CREATE_FIGURE_RECTANGLE,
    CREATE_FIGURE_CIRCLE,
    CREATE_FIGURE_TRIANGLE,
    SET_COLOR_FIGURE,
    CHANGE_OPACITY,
    SET_STROKECOLOR_FIGURE,
}